# Generated by Django 5.2.5 on 2025-08-21 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minibackend', '0002_lista_articulo_delete_cancion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='contraseña',
            new_name='password',
        ),
    ]
